# Generated by Django 3.1.1 on 2020-10-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuser',
            name='activation_token',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
