# Generated by Django 3.1.1 on 2020-09-28 05:47

from django.db import migrations, models
import django.db.models.deletion
import store.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=16)),
                ('middle_name', models.CharField(default='', max_length=16)),
                ('last_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('selling_price', models.FloatField(validators=[store.validators.validate_positive])),
                ('buying_price', models.FloatField(validators=[store.validators.validate_positive])),
                ('id', models.UUIDField(default='<functio', editable=False, primary_key=True, serialize=False)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.ImageField(default='default.jpg', upload_to='item_images')),
                ('archived', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=128)),
                ('summary', models.TextField(default='This is a book!')),
                ('publication_year', models.PositiveIntegerField()),
                ('isbn', models.CharField(max_length=13, validators=[store.validators.validate_isbn])),
                ('rating', models.FloatField(default=0, validators=[store.validators.validate_rating])),
                ('edition', models.PositiveIntegerField(default=0)),
                ('authors', models.ManyToManyField(to='store.Author')),
                ('genres', models.ManyToManyField(to='store.Genre')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.publisher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
