# Generated by Django 3.1.1 on 2020-11-14 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201112_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.publisher'),
        ),
    ]
