# Generated by Django 3.1.1 on 2020-11-26 06:08

import address.models
from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('users', '0003_storeuser_is_employee'),
        ('store', '0004_booksearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedbook',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orderedbook',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='orderedbook',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderedbook',
            name='user',
        ),
        migrations.AddField(
            model_name='orderedbook',
            name='price',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderedbook',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='quantity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='promotion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.promotion'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.storeuser'),
        ),
        migrations.AlterField(
            model_name='orderedbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.book', verbose_name='item'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], default=store.models.Order.ORDERED, max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('book', models.ManyToManyField(to='store.Book')),
                ('promotion', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.promotion')),
                ('shipping_address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.storeuser')),
            ],
        ),
        migrations.AddField(
            model_name='orderedbook',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='order'),
            preserve_default=False,
        ),
    ]
