# Generated by Django 3.1.1 on 2020-09-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200928_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
